### ISSUE TITLE
no music

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#115]
Hello,

war1gus plays no music when I launch it, no music for the aim menu, no music during the game...
my terminal log:
https://pastebin.com/ZwCr9tqY

Thank you for your help.

Config:
Ubuntu 17.10

**Comment by timfel** [comment]
You are missing ffmpeg2theora.

**Comment by legluondunet** [comment]
yet installed:

$ sudo apt-get install ffmpeg2theora timidity
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
ffmpeg2theora est déjà la version la plus récente (0.30-1build1).
timidity est déjà la version la plus récente (2.13.2-40.5).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.

**Comment by timfel** [comment]
Ah, yes, 0.30 ... this is an ffmpeg2theora bug, the older versions work, but the newer ones crash during conversion, leaving you without music. Somebody did a pull request to switch to ffmpeg on wargus, we will have to apply the same logic to war1gus.

**Comment by legluondunet** [comment]
no news about this bug, it is very annoying for Ubuntu (and perhaps Debian?) users.

**Comment by timfel** [comment]
Opened a PR, have to wait until the weekend to test it: https://github.com/Wargus/war1gus/pull/118

**Comment by guymanstuff** [comment]
Hello, I was curious if there were anymore developments on this. I am actually running war1gus on a raspberrypi and am seeing this issue.

**Comment by timfel** [comment]
The midi issue should be fixed in trunk.

**Comment by legluondunet** [comment]
Hello, you closed this issue but it is not resolved, I just try with last github version, the script still use ffmpeg theora wich produce 0 byte ogg files.

**Comment by timfel** [comment]
Yes, sorry about that, when I went over the issues I only focused on the midi issue and forgot to merge the PR for ffmpeg use. It's merged now, I'll release 2.4.2.1 as a hotfix

**Comment by legluondunet** [comment]
I confirm it works, thanks!
